<h1>Opinion</h1>
<?php $collection = $this->getReviewsCollection(); ?>
<?php foreach ($collection as $reviews): ?>
<h4> Opinion Id : <?php echo $reviews['opinion_id']; ?><br>
    Customer Id : <?php echo $reviews['customer_id']; ?><br>
    Description : <?php echo $reviews['description']; ?><br>
    Advantage : <?php echo $reviews['advantage']; ?><br>
    Disadvantage : <?php echo $reviews['disadvantage']; ?><br>
    Rating : <?php echo $reviews['rating']; ?><br>
    Recommend : <?php echo $reviews['recommend']; ?><br>
    <?php endforeach; ?>
    <br>

    <form action="<?php echo Mage::getUrl('sasha_reviews/review/create') ?>" method="post">

        <h3>Create</h3>
        Description
        <br>
        <input type="text" name="description" size="10"><br>
        Advantage
        <br>
        <input type="text" name="advantage" size="10"><br>
        Disadvantage
        <br>
        <input type="text" name="disadvantage" size="10"><br>
        <br>

        <p><input type="submit" value="Create"></p>
    </form>

    <br>

    <form action="<?php echo Mage::getUrl('sasha_reviews/review/update') ?>" method="post">

        <h3>Update</h3>
        Opinion Id
        <br>
        <input type="number" name="opinion_id" size="10"><br>
        Description
        <br>
        <input type="text" name="description" size="10"><br>
        Advantage
        <br>
        <input type="text" name="advantage" size="10"><br>
        Disadvantage
        <br>
        <input type="text" name="disadvantage" size="10"><br>
        <br>

        <p><input type="submit" value="Update"></p>
    </form>
    <br>

    <form action="<?php echo Mage::getUrl('sasha_reviews/review/delete') ?>" method="post">
        <h3>Delete</h3>
        Opinion Id
        <br>
        <input type="number" name="opinion_id" size="10"><br>
        <br>

        <p><input type="submit" value="Delete"></p>
    </form>



