<h1><?php echo $this->__('Opinion') ?></h1>
<?php $collection = $this->getReviewsCollection(); ?>
<?php //foreach ($collection as $reviews): ?>
<!--<h4> Opinion Id : --><?php //echo $reviews['opinion_id']; ?><!--<br>-->
<!--    Customer Id : --><?php //echo $reviews['customer_id']; ?><!--<br>-->
<!--    Description : --><?php //echo $reviews['description']; ?><!--<br>-->
<!--    Advantage : --><?php //echo $reviews['advantage']; ?><!--<br>-->
<!--    Disadvantage : --><?php //echo $reviews['disadvantage']; ?><!--<br>-->
<!--    Rating : --><?php //echo $reviews['reting']; ?><!--<br>-->
<!--    Recommend : --><?php //echo $reviews['recommend']; ?><!--<br>-->
<!--    Data Add : --><?php //echo $reviews['data_add']; ?><!--<br>-->
<!--    --><?php //endforeach; ?>

<?php if (Mage::getSingleton('customer/session')->isLoggedIn()): ?>
    <br>
    <form name="create-opinion-form" id="create-opinion-form"
          action="<?php echo Mage::getUrl('sasha_reviews/review/create') ?>" method="post">
        <h3><?php echo $this->__('Create') ?></h3>
        <?php echo $this->__('Description') ?><br><input type="text" name="description" class="input-text required-entry"/><br>
        <?php echo $this->__('Advantage') ?><br><input type="text" name="advantage" class="input-text required-entry"/><br>
        <?php echo $this->__('Disadvantage') ?><br><input type="text" name="disadvantage" class="input-text required-entry"/><br><br>
        <?php echo $this->__('Recommend') ?><br><input type="radio" name="recommend" value="yes" required> <?php echo $this->__('Yes') ?><br>
        <input type="radio" name="recommend" value="no" required> <?php echo $this->__('No') ?><br>
        <br>
        <?php echo $this->__('Rating') ?><br>
        <input type="radio" name="rating" value="1" required> 1<br>
        <input type="radio" name="rating" value="2"> 2<br>
        <input type="radio" name="rating" value="3"> 3<br>
        <input type="radio" name="rating" value="4"> 4<br>
        <input type="radio" name="rating" value="5"> 5<br>
        <input type="hidden" name="productId" value="<?php echo Mage::registry('product')->getId(); ?>"/>
        <input type="hidden" name="customerId"
               value="<?php echo Mage::getSingleton('customer/session')->getCustomerId(); ?>"/>

        <p><input type="submit" value="<?php echo $this->__('Create') ?>"></p>
    </form>
    <br>
    <script type="text/javascript">
        //< ![CDATA[
        var createOpinionForm = new VarienForm('create-opinion-form');
        //]]>
    </script>
<?php endif ?>

